### ISSUE TITLE
[bug] Description not visible

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/discussion-forum#1]
After clicking a particular discussion the description should be visible as a card

**Comment by Hrx4** [comment]
Hey @Priyanshi662  assign this issue to me

**Comment by Hrx4** [comment]
I saw that in every api call it gives error as the token is not valid. So is it under this issue? or I have to create separate issue for this

**Comment by Priyanshi662** [comment]
you can create a seperate issue for that , as this issue addresses creating description box after clicking on the particular forum

**Comment by Priyanshi662** [comment]
closing as completed #11
