### ISSUE TITLE
Enhancement: Improve Navbar Appearance and Layout

### ISSUE THREAD

**Issue by ramith-kulal** [Priyanshi662/discussion-forum#16]
### Issue

The current appearance and layout of the navbar in the application are not visually appealing, and the buttons are colliding, making it look unattractive. This issue is created to address the need for enhancing the navbar to improve its overall appearance and layout.
### Proposed Changes

The following improvements are suggested:
- Adjust the spacing and layout of the navbar elements to prevent button collisions.
- Enhance the visual aesthetics for a more polished look.
- Ensure consistent and pleasing design across different screen sizes.
### Screenshot of current navbar:
![Screenshot 2024-01-19 231719](https://github.com/Priyanshi662/discussion-forum/assets/142984776/27d453a6-08fa-4a1c-a086-fa45d9b5174d)

### Changes i have made:
![Screenshot 2024-01-19 232750](https://github.com/Priyanshi662/discussion-forum/assets/142984776/4d0a5c08-b377-4d69-9ce4-a417280a3d1f)

**Working under JWoC'24**

**Comment by Priyanshi662** [comment]
@ramith-kulal assigned!

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by vishal2005025** [comment]
Mam, I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by Priyanshi662** [comment]
@vishal2005025 please start working on this

**Comment by vishal2005025** [comment]
Ok
