### ISSUE TITLE
Improve Dark Mode

### ISSUE THREAD

**Issue by Surajit0573** [Priyanshi662/discussion-forum#22]
Current Dark mode is not good. In dark mode texts are not visible, and navbar not changing color or anything. I want to improve it.

![image](https://github.com/Priyanshi662/discussion-forum/assets/111490250/2e0d3486-4684-4899-84de-0e4bde5f340a)

Please assign me under JWOC  2024, if approved.

**Comment by Priyanshi662** [comment]
@Surajit0573 please start working on this issue
