### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sristy17** [Priyanshi662/discussion-forum#24]
Enhancing buttons and adding features.

jwoc

**Comment by Priyanshi662** [comment]
@sristy17 please open new issues for the PRs , as it will not be counted in leaderboard if the issues will be duplicate

**Comment by sristy17** [comment]
Can I open different issue for this pr?!

**Comment by sristy17** [comment]
> @sristy17 please open new issues for the PRs , as it will not be counted in leaderboard if the issues will be duplicate


created a new issue for the pr, please review!
