### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/discussion-forum#3]
Add photos of the application and explain the features, you can also fix any grammatical mistakes

**Comment by thatguywhocode** [comment]
Hey @Priyanshi662 ,I would like to contribute under JWOC.

**Comment by swetasingh8844** [comment]
@Priyanshi662 , please assign this to me

**Comment by thatguywhocode** [comment]
Hey @Priyanshi662 , I have created pr under JWOC.
