### ISSUE TITLE
[ui improvement] : style submit button like twitter

### ISSUE THREAD

**Issue by SHABIN-K** [Priyanshi662/discussion-forum#4]
![Screenshot 2024-01-15 224328](https://github.com/Priyanshi662/discussion-forum/assets/73272797/2fffbaf4-7da4-4fd7-b8a0-36bba647ba56)

**Comment by SHABIN-K** [comment]
can you change label easy to medium or hard

**Comment by Priyanshi662** [comment]
Closing as done #8
